test_that("pkgdown brand defines dark contrast palette", {
  palette <- read_pkgdown_brand()$color$palette

  expect_named(
    palette[c(
      "dk-black",
      "dk-gray",
      "dk-blue",
      "dk-green",
      "dk-orange",
      "dk-red",
      "dk-purple",
      "dk-code"
    )],
    c(
      "dk-black",
      "dk-gray",
      "dk-blue",
      "dk-green",
      "dk-orange",
      "dk-red",
      "dk-purple",
      "dk-code"
    )
  )

  expect_equal(palette[["dk-gray"]], "#a8b3c1")
  expect_equal(palette[["dk-blue"]], "#79b8ff")
  expect_equal(palette[["dk-code"]], "#ff8cc8")
})

test_that("pkgdown CSS consumes but does not define brand variables", {
  css <- read_pkgdown_css()
  css_text <- paste(css, collapse = "\n")

  brand_definitions <- extract_css_vars(
    css_text,
    "--brand-[A-Za-z0-9_-]+[[:space:]]*:"
  )
  brand_uses <- extract_css_vars(css_text, "var\\(--brand-[A-Za-z0-9_-]+\\)")

  expect_length(brand_definitions, 0)
  expect_gt(length(brand_uses), 0)
})

test_that("CSS only uses brand variables generated by pkgdown brand", {
  css <- paste(read_pkgdown_css(), collapse = "\n")
  palette_names <- names(read_pkgdown_brand()$color$palette)
  generated_vars <- paste0(
    "--brand-",
    gsub("-", "_", palette_names, fixed = TRUE)
  )
  used_vars <- extract_css_vars(css, "var\\((--brand-[A-Za-z0-9_-]+)\\)")
  used_vars <- sub("^var\\(", "", sub("\\)$", "", used_vars))

  expect_setequal(setdiff(used_vars, generated_vars), character())
})
